apiVersion: v1
kind: Service
metadata:
  name: ordering-service
  labels:
    app: ordering-service
spec:
  type: ClusterIP
  selector:
    app: ordering-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
